language: cpp
compiler:
  - gcc
env:
  matrix:
    - GCC_VER=4.6
    - GCC_VER=4.8


  global:
    - secure: eiaR6pXiiEpyB8+LLQ1NvZdl0Yylru1BLy9lMoHl+IpUNGGQGywmW/2WAn77rFfmR1OPA2qWQLfgPwgK0HxUA9HHlot9tre5QhiN2Lw8NOT8tCZ6tTm2+QntDBjBGJyal/knRvQkn/6qs6GxlXRerz4ArnnuPL1vESt3zwB0YtU=
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "LfolGjP8tWm3yAwthfu3yp8Zn40aueFae580UUR34gusG87cyglq2tQDtxdy+63gWEeNfArbv9n5rZv+bDW3ggHyPjuCKKc1PlZAy07lfXUXf1uz+SFhNvNoYTn3mQG3VZ08o116p4Le2p8yqu4bylJ8wckEq7PrTwvSGVQWTWM="

before_install:
  - sudo pip install cpp-coveralls
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update
  - sudo apt-get install -qq g++-4.8
  - if [ "$GCC_VER" = "4.8" ]; then export CXX="g++-4.8" CC="gcc-4.8" GCOV="gcov-4.8"; fi
script: 
  - cmake -D ENABLE_COVERAGE:BOOL=TRUE -D CMAKE_BUILD_TYPE:STRING=Debug .
  - make -j2
  - make test
  - coveralls -e "unittests/catch.hpp" -E ".*\.cpp"  --gcov $GCOV
after_script:
  - contrib/codeanalysis/runcppcheck.sh
notifications:
  email:
    recipients:
      - jason@emptycrate.com
    on_success: always
    on_failure: always
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4be9a2720eaa1bb2a6c9
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

addons:
  coverity_scan:
    project:
      name: "ChaiScript/ChaiScript"
      description: "Build submitted via Travis CI"
    notification_email: jason@emptycrate.com
    build_command_prepend: "cmake . ; make clean"
    build_command:   "make -j2"
    branch_pattern: coverity_scan


