language: cpp clang
compiler:
  - gcc
before_install:
    - sudo pip install cpp-coveralls --use-mirrors
script: 
  - cmake -D ENABLE_COVERAGE:BOOL=TRUE -D CMAKE_BUILD_TYPE:STRING=Debug -D UNIT_TEST_LIGHT:BOOL=TRUE -D USE_LIBCXX:BOOL=FALSE .
  - make
  - make test
  - coverall -x hpp
notifications:
  recipients:
    - jason@emptycrate.com
  email:
    on_success: always
    on_failure: always

