language: objective-c
compiler:
  - gcc
before_install:
    - sudo pip install cpp-coveralls
script: 
  - cmake -D ENABLE_COVERAGE:BOOL=TRUE -D CMAKE_BUILD_TYPE:STRING=Debug .
  - make -j2
  - make test
  - mkdir gcov
  - find CMakeFiles/ -name "*.gc*" -exec mv {} gcov/ \;
  - gcov -d -o gcov gcov/*.gcda
  - coveralls -n -E ".*\.cpp"
notifications:
  recipients:
    - jason@emptycrate.com
  email:
    on_success: always
    on_failure: always

