language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get install libboost-dev
script: 
  - mkdir build
  - cd build
  - cmake ../
  - make
  - make test
notifications:
  recipients:
    - jason@emptycrate.com
  email:
    on_success: always
    on_failure: always

